name: personal_task_manager_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  go_router: ^6.5.6
  get_it: ^7.2.0
  fl_three_state_switch: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
